// src/components/About.vue
<template>
    <div class="d-flex align-items-center content margin " id="landing-top">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h5 class="about-content-small">Hi, I’m Campbell
                    </h5>
                    <div class="mb-5">

                        <h1 class="mt-4 about-content mb-5">
                            I am full stack software engineer with a passion for crafting digital solutions

                        </h1>
                        <p class="about-content-small">Contact me -
                            <a class="email-link" href="mailto:campbellsfrost@gmail.com">campbellsfrost@gmail.com</a>
                        </p>
                    </div>
                </div>
                <div class="col-md-6 mb-5 d-flex justify-content-center margin-3">
                    <img src="./images/me_rock.png" class="img-fluid" alt="Picture of Campbell Frost">
                </div>
            </div>
        </div>
    </div>
</template>

<style scoped>


.about-content-small{
    font-weight: 600;
    font-size: 30px;
}
.about-content {
    font-weight: 600;
    font-size: 52pt;
}


.email-link {
    padding-bottom: 3px;
    border-bottom: 1px solid #000;
    color: #000;
    text-decoration: none;
    transition: .2s ease-out;
    -webkit-transition: .2s ease-out
}

.email-link:hover {
    text-decoration: none;
    background-color: #000;
    color: #fff
}
.margin {
    margin-top: 40px;
}




.img-fluid {
    height: 100%;
    width: 100%;
    object-fit: contain;
}

</style>

// components/about.tsx
import { HeroHighlight, Highlight } from "@/components/ui/hero-highlight";
import { CardBody, CardContainer, CardItem } from "./ui/3d-card";

import Image from "next/image";

export default function About() {
    return (
        <HeroHighlight>
            <CardContainer className="container mx-auto">
                <CardBody className="flex flex-wrap items-center justify-between dark:hover:shadow-2xl dark:hover:shadow-emerald-500/[0.1] dark:border-white/[0.2] border-black/[0.1] w-auto  h-auto rounded-xl p-6 border">

                    <div className="w-full md:w-1/2 mb-10 md:mb-0">
                        <CardItem
                            translateZ="80"
                            className="text-xl font-bold text-neutral-600 dark:text-white"
                        >
                            Hi, I'm Campbell
                        </CardItem>
                        <CardItem
                            as="p"
                            translateZ="150"
                            className="text-white text-6xl mt-6 dark:text-white font-bold mb-10 leading-tight"
                        >
                            I am a full stack <Highlight>software engineer</Highlight> with a passion for crafting digital solutions
                        </CardItem>
                        <CardItem
                            translateZ="80"
                            className="text-white text-lg font-semibold"
                        >
                            <h5 >Contact me - <a href="mailto:campbellsfrost@gmail.com" className="email-link">campbellsfrost@gmail.com</a></h5>
                        </CardItem>
                    </div>
                    <div className="w-full md:w-1/3">
                        <CardItem translateZ="150" className="w-full mt-4">
                            <Image
                                src="/images/me_rock.png"
                                height="1500"
                                width="1500"
                                className="w-full object-cover rounded-xl group-hover/card:shadow-xl"
                                alt="thumbnail"
                            />
                        </CardItem>
                    </div>
                </CardBody>
            </CardContainer>
        </HeroHighlight>
    );
}
