// src/components/Navbar.vue
<template>
    <div class="fixed-top" id="navigation">
        <nav class="navbar navbar-expand-lg primary-nav container my-1">
        
                <a aria-current="page" class="nav-item nav-link mx-2 py-2 primary" href="/">Campbell Frost</a>
        
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="navbar-nav ms-auto">

                    <a class="nav-item nav-link mx-3" href="https://github.com/campbell-frost" target="__blank">Github
                    </a>
                    <a class="nav-item nav-link mx-3" href="https://www.linkedin.com/in/campbell-frost-39656a207/"
                        target="__blank">Linkedin
                    </a>
                    <a class="nav-item nav-link mx-3" href="https://www.instagram.com/campbell.frost/"
                        target="__blank">Instagram
                    </a>
                    <a class="btn btn-layered offset square mx-3" href="mailto:campbellsfrost@gmail.com" role="button"
                        aria-pressed="true">Email Me
                    </a>
                </div>
            </div>
        </nav>
    </div>
</template>

<style scoped>
#navigation {
    font-weight: 500;
    font-size: x-large;
    border-bottom: 1px solid #000;
    background-color: white;
}

.primary {
    font-weight: 600;
    margin-left: 2px;
    margin-right: 2px;
}

.offset {
    box-shadow: .4em .3em 0 0 #000;
    border-radius: 0px;
}

.offset:focus,
.offset:hover {
    box-shadow: 0 0 0 0 #000000;
    color: #000;
    text-decoration: none;
    border-radius: 0px;
}

.btn-layered {
    background: none;
    border: 2px solid #000;
    line-height: 1rem;
    padding: 10px 26px;
    padding-top: 15px;
    transition: .1s ease-out;
    -webkit-transition: .1s ease-out;
    color: #000;
    max-width: 140px;
    font-size: 20px;
}

.hamburger {
    max-width: 20px;
}

.navbar-toggler {
    outline: none;
    border: none;

}

.navbar-toggler:focus {
    box-shadow: none;
}

.nav-link {
    border-bottom: 2px solid white;
    color: black;
    font-weight: 600;
}

.nav-link:hover,
.nav-link:focus {
    border-bottom: 2px solid black;
}
</style>

// components/navbar.tsx
'use client'
import React from 'react';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"

const Navbar = () => {
    return (
        <div className="fixed top-0 left-0 right-0 z-50 bg-black" id="navigation">
            <nav className=" bg-transparent py-1">
                <div className="container mx-auto">
                    <div className="flex justify-between items-center">
                        <a href="/" className="text-white text-xl font-bold py-2">Campbell Frost</a>
                        <DropdownMenu>
                            <DropdownMenuTrigger>
                                <a
                                    className="block lg:hidden focus:outline-none"
                                    type="button"
                                    aria-label="Toggle navigation"
                                >
                                    <span className="text-white text-3xl">&#8801;</span>
                                </a>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent className="bg-black mr-7 border-none">
                                <div className="text-white bg-black border border-white border-opacity-20 rounded-lg ">
                                    <DropdownMenuItem>
                                        <a href="https://github.com/campbell-frost" target="_blank" rel="noopener noreferrer">Github</a>
                                    </DropdownMenuItem>
                                    <DropdownMenuItem>
                                        <a href="https://www.linkedin.com/in/campbell-frost-39656a207/" target="_blank" rel="noopener noreferrer">LinkedIn</a>
                                    </DropdownMenuItem>
                                    <DropdownMenuItem>
                                        <a href="https://www.instagram.com/campbell.frost/" target="_blank" rel="noopener noreferrer">Instagram</a>
                                    </DropdownMenuItem>
                                    <DropdownMenuItem>
                                        <a href="mailto:campbellsfrost@gmail.com">Email Me</a>
                                    </DropdownMenuItem>
                                </div>
                            </DropdownMenuContent>
                        </DropdownMenu>
                        <div className="hidden lg:flex lg:flex-grow lg:items-center lg:w-auto lg:justify-end">
                            <div className="lg:flex lg:flex-row lg:ml-auto text-white text-lg">
                                <a
                                    href="https://github.com/campbell-frost"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="nav-link mx-3"
                                >
                                    Github
                                </a>
                                <a
                                    href="https://www.linkedin.com/in/campbell-frost-39656a207/"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="nav-link mx-3"
                                >
                                    LinkedIn
                                </a>
                                <a
                                    href="https://www.instagram.com/campbell.frost/"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="nav-link mx-3"
                                >
                                    Instagram
                                </a>
                                <a
                                    href="mailto:campbellsfrost@gmail.com"
                                    className="btn-layered offset square mx-3"
                                    role="button"
                                    aria-pressed="true"
                                >
                                    Email Me
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    );
};

export default Navbar;
