// components/ui/about.tsx
import { Highlight } from "@/components/ui/hero-highlight";

export default function About() {
    return (
        <div className="container mx-auto px-8">
            <div className="flex flex-wrap items-center justify-between pt-40">
                <div className="w-full md:w-1/2 mb-10 md:mb-0">

                    <h5 className="text-white text-4xl font-semibold mb-5 ">Hi, I’m Campbell</h5>
                    <div className="mb-5">
                        <h1 className="text-white text-6xl font-bold mb-10 leading-tight">
                            I am a full stack <Highlight>software engineer</Highlight> with a passion for crafting digital solutions
                        </h1>

                        <p className="text-white text-lg font-semibold">Contact me - <a href="mailto:campbellsfrost@gmail.com" className="email-link">campbellsfrost@gmail.com</a></p>
                    </div>
                </div>
                <div className="w-full md:w-1/3 ">
                    <img src="./images/me_rock.png" className="w-full border-radius" alt="Picture of Campbell Frost" />
                </div>
            </div>

        </div>
    );
}

// src/components/About.vue
<template>
    <div class="d-flex align-items-center content margin " id="landing-top">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h5 class="about-content-small">Hi, I’m Campbell
                    </h5>
                    <div class="mb-5">
                        <h1 class="my-5 about-content">
                            I am full stack software engineer with a passion for crafting digital solutions
                        </h1>
                        <p class="about-content-small">Contact me -
                            <a class="email-link" href="mailto:campbellsfrost@gmail.com">campbellsfrost@gmail.com</a>
                        </p>
                    </div>
                </div>
                <div class="col-md-6 mb-5 d-flex justify-content-center margin-3">
                    <img src="./images/me_rock.png" class="img-fluid border-radius" alt="Picture of Campbell Frost">
                </div>
            </div>
        </div>
    </div>
</template>

<style scoped>
.about-content-small {
    font-weight: 600;
    font-size: 30px;
}

.about-content {
    font-weight: 700;
    font-size: 52pt;
}
@media (max-width: 1400px) {
    .about-content {
        font-size: 58px;
    }
}

@media (max-width: 1200px) {
    .about-content {
        font-size: 43px;
    }
}

@media (max-width: 1000px) {
    .about-content {
        font-size: 34px;
        font-weight: 700;
    }
}


.email-link {
    padding-bottom: 3px;
    border-bottom: 1px solid #000;
    color: #000;
    text-decoration: none;
    transition: .2s ease-out;
    -webkit-transition: .2s ease-out
}

.email-link:hover {
    text-decoration: none;
    background-color: #000;
    color: #fff
}

.margin {
    margin-top: 40px;
}

.border-radius {
    border-radius: 8px;
}

.img-fluid {
    height: 100%;
    width: 100%;
    object-fit: contain;
    border-radius: 8px;
}
</style>
